<template>
    
  <CustomCursor></CustomCursor>

  <div class="header-top pt-6 d-none d-lg-block transition position-absolute w-100 z-index-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10">
          <div class="d-flex justify-content-center align-items-center flex-wrap gap-3">
            <a href="#" class="link d-inline-block py-1 px-2 rounded secondary-fixed on-secondary-fixed-variant ff-1 fs-12 lh-1 fw-bold text-center flex-shrink-0"> Limited Offer </a>
            <span class="d-block ff-1 fs-12 fw-semibold clr-white"> Sign up and receive 20% bonus discount on checkout. </span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <Header></Header>
  
  <section class="breadcrumb-section">
    <div class="breadcrumb-section-inner">
      <div class="container">
        <div class="row g-4 justify-content-center">
          <div class="col-xxl-5 col-xl-8">
            <div class="text-center">
              <div class="d-inline-flex align-items-center py-2 px-4 bg-info-10 bg-opacity-3 rounded-1">
                <span class="fs-12 clr-white">Social Mind AI</span>
              </div>
              <h2 class="h3 fw-bold clr-neutral-87 mt-4 mb-0">Terms and Services</h2>
            </div>
          </div>
          <div class="col-xl-8">
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> Acceptance of Terms </h5>
              <p class="clr-neutral-80"> By registering for or using Social Mind, you agree to be bound by these Terms and
                Conditions. If you do not agree, please do not use our services </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90">  Use of Services </h5>
              <p class="clr-neutral-80"> Social Mind provides tools to help you manage social media content, schedule posts,
                and analyze audience engagement. You agree to use our services responsibly and only
                for legal purposes. </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> Account Responsibility </h5>
              <p class="clr-neutral-80">  You are responsible for maintaining the security and confidentiality of your account credentials. Any activity conducted through your account is your responsibility. </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> User Conduct</h5>
              <p class="clr-neutral-80">  You agree not to misuse the platform for any unlawful or prohibited activity, including unauthorized access, data scraping, or harmful conduct </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90">  Subscription and Payment</h5>
              <p class="clr-neutral-80">  Certain features on Social Mind may require a paid subscription. Payment terms will be
                specified at the time of purchase, and all sales are final unless otherwise specified. </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> Intellectual Property</h5>
              <p class="clr-neutral-80">  Content generated by users, including any posts, descriptions, tags, or other materials
                created using Social Mind's tools, remains the intellectual property of the user who
                created it. Social Mind does not claim ownership of this user-generated content. Users
                retain all rights and control over this content, including any rights to edit, delete, or
                distribute it. </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> Limitation of Liability</h5>
              <p class="clr-neutral-80">  Social Mind shall not be liable for any direct, indirect, incidental, or consequential
                damages arising from your use or inability to use the service. </p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90">  Termination</h5>
              <p class="clr-neutral-80">  We reserve the right to suspend or terminate your access to Social Mind at any time if
                we believe you are in violation of these terms.</p>
            </div>
            <div class="section-space-xsm-y">
              <h5 class="clr-neutral-90"> Changes to Terms</h5>
              <p class="clr-neutral-80">  Social Mind reserves the right to change or modify these terms at any time. Continued
                use of the site implies acceptance of these changes.</p>
                <p class="clr-neutral-80">  For any questions regarding these terms, please contact us at support@socialmind.com.
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <img src="../../../public/img/breadcrumb-shape-top.png" alt="image" class="img-fluid breadcrumb-shape breadcrumb-shape-top">
    <img src="../../../public/img/breadcrumb-shape-left.png" alt="image" class="img-fluid breadcrumb-shape breadcrumb-shape-left">
    <img src="../../../public/img/breadcrumb-shape-right.png" alt="image" class="img-fluid breadcrumb-shape breadcrumb-shape-right">
    <img src="../../../public/img/breadcrumb-shape-line-left.png" alt="image" class="img-fluid breadcrumb-shape breadcrumb-shape-line-left">
    <img src="../../../public/img/breadcrumb-shape-line-right.png" alt="image" class="img-fluid breadcrumb-shape breadcrumb-shape-line-right">
  </section>

<Footer></Footer>


</template>

<script setup>
import { RouterLink, RouterView } from 'vue-router'

import Footer from "./Footer.vue";
import CustomCursor from "./CustomCursor.vue"
import Header from "./Header.vue"

</script>